### ISSUE TITLE
Should we have some way to contact the team if people are interested in getting involved?  Or assume that anyone savvy enough, could figure it out?

### ISSUE THREAD

**Issue by jracusin** [ComPair/website#6]
We mention on the team page that people should contact Julie, but provide no contact details.

**Comment by reginacaputo** [comment]
This could be our bar to joining the collaboration... ;)

**Comment by kialio** [comment]
I think that we shouldn't put specific contact details on the site (or a form).  My thought is that people that want to join will know how to contact Julie (or someone that can).  I'm assigning this issue to Julie to make the final decision.

**Comment by mcenery** [comment]
I like the way it is now. Any scientist should easily be able to figure  out how to get my email. If we put contact details, I might end up spammed horribly.
